# Generated by Django 5.2.7 on 2025-10-04 17:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrestationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_name', models.CharField(max_length=200)),
                ('requester_email', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=300)),
                ('domain', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('equipment_list', models.JSONField(blank=True, default=list)),
                ('methodology', models.TextField(blank=True)),
                ('analysis_types', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('submitted', 'Soumis'), ('evaluated', 'Évalué'), ('validated', 'Validé'), ('planned', 'Planifié'), ('in_progress', 'En cours'), ('done', 'Terminé'), ('rejected', 'Rejeté')], default='submitted', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('planned_start', models.DateTimeField(blank=True, null=True)),
                ('planned_end', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=1)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='labo.lab')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('demandeur', 'Demandeur'), ('technician', 'Technicien'), ('responsible', 'Responsable'), ('dg', 'Directeur General')], default='demandeur', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_text', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='labo.prestationrequest')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_start', models.DateTimeField()),
                ('scheduled_end', models.DateTimeField()),
                ('assigned_to', models.CharField(blank=True, max_length=200)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='labo.prestationrequest')),
            ],
        ),
    ]
